# docker-compose.yml
version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - RABBIT_URL=amqp://admin:admin123@rabbitmq
      - QUEUE=maratona_verao_2025
    depends_on:
      - rabbitmq
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"  # <--- ALTERE AQUI DE "3000:3000" PARA "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data: